# ============================================================
# prompts.py — Prompt Templates for MedGemma
# RehabFlow AI — MedGemma Impact Challenge 2026
# ============================================================

# ---------------------------------------------------------------------------
# System prompt: Sets the AI's role, safety guardrails, and output format
# ---------------------------------------------------------------------------
INITIAL_PLAN_SYSTEM_PROMPT = """You are RehabFlow AI, a licensed physiotherapist with 15+ years of clinical experience creating safe, evidence-based home rehabilitation plans for musculoskeletal conditions.

## Your Core Principles
1. **Safety First** — Always screen for red flags and contraindications before prescribing exercises.
2. **Progressive Overload** — Start conservatively and build up gradually over 14 days.
3. **Patient Empowerment** — Educate the patient on *why* each exercise helps.
4. **Home-Friendly** — Only prescribe exercises using bodyweight or common household items (towel, chair, wall, pillow).
5. **Pain-Guided Progression** — If pain increases above baseline, regress the program.

## Output Format (STRICT — use these exact markdown sections)
Output **only** clean, professional markdown with these exact sections:

### 🏥 Patient Overview
Brief summary of the patient's condition, goals, and current limitations.

### 📋 Clinical Assessment
- Pain analysis and likely contributing factors
- Functional limitations
- Precautions and contraindications

### 🗓️ 14-Day Rehab Plan
A detailed markdown table with columns:
| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |

### 📈 Progression Rules
- When to progress (pain ≤3/10 for 2 consecutive days)
- When to regress (pain >6/10 or new symptoms)
- Weekly milestones

### ⚠️ Safety & Red Flags
List specific warning signs that require IMMEDIATE medical attention:
- Sudden severe pain, numbness, tingling
- Joint locking, giving way
- Swelling that doesn't resolve
- Fever with joint pain

### 📊 Daily Tracking Instructions
How to log pain, range of motion, and exercise completion.

### ⚕️ Disclaimer
> **IMPORTANT**: This plan is generated by an AI assistant for educational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider before starting any rehabilitation program. If you experience severe pain, numbness, or any concerning symptoms, stop immediately and seek medical attention.

## Rules
- Never diagnose specific pathology from images alone; describe what you observe.
- Always err on the side of caution.
- Use plain language the patient can understand.
- Include warm-up and cool-down in every session.
"""

# ---------------------------------------------------------------------------
# User turn template: Filled with patient-specific data
# ---------------------------------------------------------------------------
INITIAL_PLAN_USER_TEMPLATE = """Please create a personalized 14-day home rehabilitation plan for the following patient:

**Patient Name:** {patient_name}
**Condition:** {condition}
**Symptoms:** {symptoms}
**Current Pain Level:** {pain_level}/10
**Image Provided:** {image_description}

### Requirements:
1. Create a realistic 14-day home exercise program with 4–6 exercises per session.
2. Use ONLY bodyweight or household items (chair, towel, wall, pillow, water bottle).
3. Start conservatively (pain should not exceed {pain_level}/10 during exercises).
4. Include specific form cues to prevent compensation patterns.
5. Add warm-up (5 min) and cool-down (5 min) to each session.
6. Provide clear progression criteria and regression options.
7. Flag any red flags specific to this condition.
"""

# ---------------------------------------------------------------------------
# Progress update prompt: Adapts existing plan based on daily check-in
# ---------------------------------------------------------------------------
PROGRESS_UPDATE_PROMPT = """You are RehabFlow AI. A patient is checking in with a progress update on their rehabilitation plan.

## Current Plan Summary
{current_plan_summary}

## Today's Check-In
**Current Pain Level:** {today_pain}/10 (was {original_pain}/10 at start)
**Patient Notes:** {progress_notes}
**Days Since Plan Started:** {days_elapsed}

## Your Task
Based on this progress update:

1. **Assess Progress** — Is the patient improving, plateauing, or worsening?
2. **Adjust the Plan** — Modify exercises, sets, reps, or intensity as needed.
3. **Address Concerns** — Respond to any specific concerns the patient raised.
4. **Update Timeline** — Adjust remaining days if needed.

### Response Format (Markdown):

#### 📊 Progress Assessment
[Your assessment of how the patient is doing]

#### 🔄 Plan Adjustments
| Change | Previous | Updated | Reason |
|--------|----------|---------|--------|

#### 📋 Updated Exercise Program (Next 3 Days)
| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |

#### ⚠️ Watch For
[Any new red flags or concerns based on the update]

#### 💬 Patient Guidance
[Encouraging, specific guidance for the patient]

#### ⚕️ Disclaimer
> This adaptation is AI-generated for educational purposes only. Consult your healthcare provider before making changes to your rehabilitation program.
"""

# ---------------------------------------------------------------------------
# PDF summary prompt: Compressed version for clean PDF export
# ---------------------------------------------------------------------------
PDF_SUMMARY_PROMPT = """Summarize the following rehabilitation plan into a clean, print-ready format.

## Plan to Summarize:
{plan_content}

## Output Format:
Create a concise summary with:
1. **Patient Info** — Name, condition, start date
2. **Exercise Table** — All 14 days in a compact table
3. **Key Precautions** — Top 5 safety points
4. **Progression Milestones** — Week 1 and Week 2 goals
5. **Emergency Signs** — When to seek immediate help
6. **Disclaimer** — Standard medical disclaimer

Keep it professional and suitable for printing on 2-3 pages.
"""

# ---------------------------------------------------------------------------
# Demo mode: Hardcoded realistic plans for testing without model
# ---------------------------------------------------------------------------
DEMO_PLANS = {
    "Knee Osteoarthritis": """## 🏥 Patient Overview
**Condition:** Bilateral Knee Osteoarthritis (Grade II)
**Primary Complaint:** Dull, aching pain in both knees, worse with stairs and prolonged sitting. Morning stiffness lasting ~20 minutes.
**Goal:** Reduce pain, improve functional mobility, and strengthen supporting musculature.

## 📋 Clinical Assessment
- **Pain Pattern:** Mechanical pain — worse with activity, better with rest. No night pain.
- **Functional Limitations:** Difficulty with stairs, squatting, and prolonged walking (>15 min).
- **Precautions:** Avoid deep squatting, high-impact activities, and loaded knee flexion beyond 90°.

## 🗓️ 14-Day Rehab Plan

### Week 1: Foundation & Pain Management (Days 1–7)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 1-2 | Quad sets (seated) | 3 × 10, hold 5s | Press knee down into towel roll | Low |
| 1-2 | Heel slides | 3 × 10 | Slide heel along bed, keep toes up | Low |
| 1-2 | Seated knee extensions | 2 × 10 | Slow and controlled, don't lock knee | Low |
| 1-2 | Calf raises (chair support) | 2 × 12 | Rise on toes, 2s hold at top | Low |
| 3-4 | All above + Standing hip abduction | 3 × 10 each leg | Hold chair, keep hips level | Low-Mod |
| 5-7 | All above + Mini wall squats | 2 × 8, hold 3s | Back against wall, knees at 45° max | Moderate |

### Week 2: Strengthening & Function (Days 8–14)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 8-10 | Step-ups (low step ~4 inches) | 3 × 8 each leg | Lead with affected leg up, control down | Moderate |
| 8-10 | Bridges | 3 × 12 | Squeeze glutes at top, 2s hold | Moderate |
| 8-10 | Seated hamstring curls (towel) | 3 × 10 | Drag heel back against towel resistance | Moderate |
| 11-14 | All above + Tandem stance | 3 × 30s each side | Heel-to-toe, light finger touch on wall | Moderate |
| 11-14 | Sit-to-stand (chair) | 3 × 10 | Arms crossed, lean forward, drive through heels | Mod-High |

## 📈 Progression Rules
- **Progress when:** Pain ≤ 3/10 for 2 consecutive days during exercises.
- **Regress when:** Pain > 6/10 during or after exercises, or new swelling develops.
- **Week 1 Goal:** Perform all exercises with pain ≤ 4/10.
- **Week 2 Goal:** Complete sit-to-stand × 10 with no hands.

## ⚠️ Safety & Red Flags
🚨 **STOP and seek medical attention if you experience:**
- Sudden, severe knee pain or locking
- Significant new swelling (warm, red joint)
- Knee giving way or buckling
- Numbness or tingling in legs/feet
- Pain that doesn't settle within 24 hours of exercise

## 📊 Daily Tracking Instructions
Log daily: (1) Morning pain /10, (2) Evening pain /10, (3) Exercises completed ✓/✗, (4) Minutes walked, (5) Any new symptoms.

## ⚕️ Disclaimer
> **IMPORTANT**: This plan is generated by an AI assistant for educational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider before starting any rehabilitation program.""",

    "Frozen Shoulder": """## 🏥 Patient Overview
**Condition:** Adhesive Capsulitis (Frozen Shoulder) — Left Shoulder, Freezing Stage
**Primary Complaint:** Progressive loss of shoulder range of motion with pain at end-range. Difficulty reaching overhead, behind back, and with dressing.
**Goal:** Maintain existing ROM, reduce pain, and gently restore mobility within pain tolerance.

## 📋 Clinical Assessment
- **Pain Pattern:** Constant dull ache with sharp pain at end-range movements. Night pain disrupting sleep.
- **Functional Limitations:** Cannot reach overhead, fasten bra, tuck shirt, or sleep on affected side.
- **Precautions:** No aggressive stretching or forcing through pain. Respect tissue healing timeline.

## 🗓️ 14-Day Rehab Plan

### Week 1: Gentle Mobility & Pain Relief (Days 1–7)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 1-3 | Pendulum swings (Codman's) | 3 × 1 min each direction | Lean on table, let arm hang, circle gently | Very Low |
| 1-3 | Towel-assisted external rotation | 3 × 10 | Hold towel behind back, gentle pull | Low |
| 1-3 | Wall finger walks (forward) | 3 × 10 | Face wall, walk fingers up, stop at first pain | Low |
| 1-3 | Supine passive flexion (stick) | 3 × 10, hold 5s | Use stick/umbrella to lift arm, relax, let stick do the work | Low |
| 4-7 | All above + Cross-body stretch | 3 × 15s hold | Use good arm to gently pull across, no pain | Low-Mod |
| 4-7 | Isometric external rotation | 3 × 8, hold 5s | Push into door frame, 30% effort, no movement | Low-Mod |

### Week 2: Progressing ROM & Light Strengthening (Days 8–14)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 8-10 | Wall finger walks (side) | 3 × 10 | Stand sideways to wall, walk fingers up | Moderate |
| 8-10 | Supine external rotation (stick) | 3 × 10, hold 5s | Elbow at 90°, use stick to rotate outward | Moderate |
| 8-10 | Prone Y-raises (pillow) | 2 × 8 | Lie face down, thumbs up, lift arms to Y shape | Moderate |
| 11-14 | All above + Band pull-aparts (light) | 3 × 12 | Use light resistance band or towel | Moderate |
| 11-14 | Side-lying external rotation (water bottle) | 2 × 10 | 500ml bottle, elbow pinned to side | Moderate |

## 📈 Progression Rules
- **Progress when:** Can complete current exercises with pain ≤ 3/10.
- **Regress when:** Night pain worsens or daytime pain increases above 5/10.
- **Week 1 Goal:** Achieve pain-free pendulum swings and 10° improvement in flexion.
- **Week 2 Goal:** Begin active-assisted movements with light resistance.

## ⚠️ Safety & Red Flags
🚨 **STOP and seek medical attention if you experience:**
- Sudden loss of all shoulder movement
- Severe pain not responding to rest or ice
- Numbness, tingling, or weakness in hand/fingers
- Fever with shoulder pain and swelling
- Traumatic onset (fall or impact)

## 📊 Daily Tracking Instructions
Log daily: (1) Pain at rest /10, (2) Pain with movement /10, (3) Best overhead reach (inches from wall), (4) Sleep quality (1-5), (5) Exercises completed.

## ⚕️ Disclaimer
> **IMPORTANT**: This plan is generated by an AI assistant for educational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider before starting any rehabilitation program.""",

    "Lumbar Disc Herniation": """## 🏥 Patient Overview
**Condition:** Lumbar Disc Herniation (L4-L5) with Mild Radiculopathy
**Primary Complaint:** Lower back pain radiating to left buttock and posterior thigh. Worse with sitting, bending forward, and coughing/sneezing.
**Goal:** Centralize symptoms, reduce radicular pain, restore core stability, and improve functional tolerance.

## 📋 Clinical Assessment
- **Pain Pattern:** Central low back pain with left-sided radiculopathy to mid-thigh (no below-knee symptoms). Peripheralizes with flexion, centralizes with extension.
- **Functional Limitations:** Cannot sit >20 min, difficulty bending forward, unable to lift objects from floor.
- **Precautions:** Avoid loaded flexion, heavy lifting, and prolonged sitting. Use directional preference (extension) approach.

## 🗓️ 14-Day Rehab Plan

### Week 1: Pain Centralization & Core Activation (Days 1–7)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 1-3 | Prone press-ups (McKenzie) | 5 × 10 | Keep hips on floor, push up with arms, sag back down | Low |
| 1-3 | Diaphragmatic breathing | 3 × 2 min | Hands on belly, breathe into hands, 4s in/6s out | Very Low |
| 1-3 | Supine pelvic tilts | 3 × 10 | Flatten back to floor, gentle squeeze | Low |
| 1-3 | Supine knee-to-chest (unaffected side only) | 3 × 10, hold 10s | Keep other leg bent with foot on floor | Low |
| 4-7 | All above + Bird-dogs | 3 × 8 each side | Opposite arm/leg, keep spine neutral, 3s hold | Low-Mod |
| 4-7 | Side plank (knees bent) | 3 × 15s each side | Elbow under shoulder, hips stacked | Moderate |

### Week 2: Core Endurance & Functional Retraining (Days 8–14)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 8-10 | Standing press-ups (wall) | 3 × 10 | Hands on wall, arch back, return | Moderate |
| 8-10 | Dead bugs | 3 × 8 each side | Press low back into floor, extend opposite limbs | Moderate |
| 8-10 | Glute bridges | 3 × 12 | Drive through heels, squeeze glutes 2s at top | Moderate |
| 11-14 | All above + Hip hinge practice (dowel) | 3 × 10 | Dowel along spine (head/mid-back/sacrum contact) | Moderate |
| 11-14 | Tall plank holds | 3 × 20s | Hands under shoulders, straight line head to heels | Mod-High |

## 📈 Progression Rules
- **Progress when:** Symptoms centralize (move toward spine) and pain ≤ 3/10 for 2 consecutive days.
- **Regress when:** Symptoms peripheralize (spread toward leg), pain > 6/10, or new neurological symptoms.
- **Week 1 Goal:** Centralize all symptoms to low back only.
- **Week 2 Goal:** Sit 30 min pain-free, perform hip hinge with neutral spine.

## ⚠️ Safety & Red Flags
🚨 **STOP and seek IMMEDIATE medical attention if you experience:**
- Loss of bladder or bowel control (EMERGENCY — cauda equina syndrome)
- Progressive weakness in legs or feet
- Numbness in groin/saddle area
- Bilateral leg symptoms (both sides)
- Severe, unrelenting pain not relieved by any position

## 📊 Daily Tracking Instructions
Log daily: (1) Back pain /10, (2) Leg pain /10 and how far down, (3) Worst position, (4) Best position, (5) Minutes tolerated sitting.

## ⚕️ Disclaimer
> **IMPORTANT**: This plan is generated by an AI assistant for educational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider before starting any rehabilitation program.""",

    "Post-ACL Reconstruction": """## 🏥 Patient Overview
**Condition:** Post-ACL Reconstruction (Hamstring Autograft) — Week 6 Post-Op
**Primary Complaint:** Knee stiffness, quadriceps weakness, difficulty with full extension and stairs. Cleared for closed-chain exercises by surgeon.
**Goal:** Restore full knee extension, improve quad strength, normalize gait pattern.

## 📋 Clinical Assessment
- **Pain Pattern:** Mild anterior knee pain (3/10), increases with end-range flexion and stairs. No instability symptoms.
- **Functional Limitations:** 5° extension deficit, flexion to 110°, significant quad atrophy (2cm circumference difference), antalgic gait.
- **Precautions:** No open-chain knee extension 0-45°, no pivoting or cutting movements, no running.

## 🗓️ 14-Day Rehab Plan

### Week 1: ROM Restoration & Quad Activation (Days 1–7)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 1-3 | Prone hangs (extension) | 3 × 2 min | Ankle on towel roll, let gravity straighten knee | Low |
| 1-3 | Quad sets (VMO focus) | 4 × 10, hold 5s | Tighten quad maximally, push knee into surface | Low |
| 1-3 | Heel slides (flexion ROM) | 3 × 15 | Slide heel toward buttock, use towel for assistance | Low |
| 1-3 | Straight leg raises (all 4 directions) | 3 × 10 each | Lock knee fully before lifting, slow lower | Low-Mod |
| 4-7 | All above + Mini squats (chair behind) | 3 × 10 | Squat to chair height, drive through heels | Moderate |
| 4-7 | Standing calf raises | 3 × 15 | Hold chair for balance, 2s pause at top | Moderate |

### Week 2: Strengthening & Functional Training (Days 8–14)

| Day | Exercises | Sets × Reps / Duration | Form Cues | Intensity |
|-----|-----------|----------------------|-----------|-----------|
| 8-10 | Step-ups (6 inch) | 3 × 10 each leg | Surgical leg leads up, control the down | Moderate |
| 8-10 | Wall sits | 3 × 30s | Back flat, knees at 60°, even weight | Moderate |
| 8-10 | Single-leg balance (flat surface) | 3 × 30s each | Eyes open, light fingertip touch on wall if needed | Moderate |
| 11-14 | All above + Lateral step-downs | 3 × 8 each | Stand on step, slowly lower opposite heel to floor | Mod-High |
| 11-14 | Standing hamstring curls (resistance band) | 3 × 12 each | Light band, control both directions | Moderate |
| 11-14 | Stationary bike (if available) | 1 × 10-15 min | Low resistance, full revolution, seat high enough | Moderate |

## 📈 Progression Rules
- **Progress when:** Pain ≤ 2/10 during exercises, no increased swelling post-exercise.
- **Regress when:** Significant swelling (>1cm increase), pain > 4/10, or feeling of instability.
- **Week 1 Goal:** Achieve 0° extension, 120° flexion, and active quad contraction.
- **Week 2 Goal:** Normal gait pattern, ascend stairs step-over-step.

## ⚠️ Safety & Red Flags
🚨 **STOP and contact your surgeon if you experience:**
- Sudden increase in swelling (warm, tight knee)
- Feeling of instability or "giving way"
- Sharp pain within the joint
- Fever, redness, or drainage from incision sites
- Popping or catching sensation
- Inability to bear weight

## 📊 Daily Tracking Instructions
Log daily: (1) Pain /10 at rest and with activity, (2) Swelling (measure circumference 1cm above kneecap), (3) ROM (extension and flexion in degrees), (4) Exercises completed, (5) Gait quality (1-5).

## ⚕️ Disclaimer
> **IMPORTANT**: This plan is generated by an AI assistant for educational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider, especially after surgical procedures.""",
}
